packages:
  - "apps/*"
  - "packages/*"
catalog:
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  typescript: ^5.8.3
  react: ^19.1.0
  react-dom: ^19.1.0
  eslint: ^9.28.0
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19
